steps:
  # Build the application with Maven
  - name: 'maven:3.9.5-eclipse-temurin-24'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-pl', 'apps/advanced-calculator-runtime', '-am']
    env:
      - 'MAVEN_OPTS=-Dmaven.repo.local=/workspace/.m2/repository'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/advanced-calculator:$COMMIT_SHA', '.']
    dir: 'apps/advanced-calculator-runtime'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/advanced-calculator:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'advanced-calculator'
      - '--image=gcr.io/$PROJECT_ID/advanced-calculator:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/advanced-calculator:$COMMIT_SHA'

# Configure timeout
timeout: '1800s'