version: '3.9'

services:
  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change_me
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    build:
      context: .
      dockerfile: keycloak.dockerfile
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change_me
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: change_me

volumes:
  keycloak_data:
