name: Build basic-calculator-runtime

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/basic-calculator/**'
      - 'apps/basic-calculator-runtime/**'
      - '.github/workflows/build-basic-calculator-runtime.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build with Maven
        run: mvn -B clean package -pl apps/basic-calculator-runtime -am
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JLink image
        uses: actions/upload-artifact@v4
        with:
          name: basic-calculator-jlink-image
          path: apps/basic-calculator-runtime/target/jlink-image