name: Publish lib-core-auth

on:
  push:
    branches: [ main ]
    paths:
      - 'libs/lib-core-auth/**'
      - '.github/workflows/publish-lib-core-auth.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build with Maven
        run: mvn -B clean verify -pl libs/lib-core-auth -am

      - name: Publish to GitHub Packages
        run: mvn -B deploy -pl libs/lib-core-auth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}